# Generated by Django 5.1.1 on 2025-03-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ThoughtProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.TextField()),
                ('related_processes', models.ManyToManyField(blank=True, to='problems.thoughtprocess')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_year', models.IntegerField()),
                ('source_university', models.CharField(max_length=255)),
                ('source_faculty', models.CharField(max_length=255)),
                ('boxURL', models.URLField(blank=True, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('good_points', models.TextField(blank=True, null=True)),
                ('usage_location', models.TextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='problems', to='problems.tag')),
                ('thought_processes', models.ManyToManyField(blank=True, related_name='problems', to='problems.thoughtprocess')),
            ],
        ),
    ]
